#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/3b1e0928-896f-4275-8d49-8fa149cd5f3d/ # 
title: Records API
#baseUri: http://localhost:8081/api
version: v1
protocols: [ HTTP, HTTPS ] 
mediaType: [ application/json ]
description: System API for the records. Current implementation supports customer records. Can be extended to support other records such as orders or products.
securitySchemes:
  basic:
    description: Basic API authentication.
    type: Basic Authentication

traits:
  noCache:
    headers:
      Cache-Control:
        type: string
        default: no-cache
  isSecure:
    securedBy: [ basic ]

types:
  Customer: !include datatypes/customer.raml
  CustomerNoId: !include datatypes/customerNoId.raml

/records:
  description: This is the topmost layer of the API which is the entry point for record queries.
  /customers:
    description: The entry point for calls related to customer records.
    get:
      description: Retrieves all customers records present in the system.
      is:
        - noCache
        - isSecure
      headers:
        Client-ID:
          description: Identifier of the client invoking the API.
          
      responses:
        200:
          description: Returns an array of customer objects in JSON.
          body:
            application/json:
              type: Customer[]
              example:  !include examples/customersExample.raml

        400:
          body:
            application/json:
              example: {
                "message": "Error retrieving data from the customer database."
              }
    
    post:
      description: Creates new customers from the customer object in request.
      is:
        - noCache
        - isSecure
      headers:
          Client-ID:
            description: Identifier of the client invoking the API.
            required: true
      body:
        application/json:
          description: Payload should be a customer object with all fields present.
          type: CustomerNoId
          example: !include examples/customerExampleNoId.raml
      responses:
        201:
          description: Customer object created successfully.
          body:
            application/json:
              example: !include examples/customerExample.raml
        400:
          body:
            application/json:
              example: {
                "message": "Error creating customer. Please check the request and make sure it is valid."
              }

    /{id}:
      get:
        is:
          - noCache
          - isSecure
        headers:
          Client-ID:
            description: Identifier of the client invoking the API.
            required: true
        description: Retrieve a customer by the customer id
        responses:
          200:
            body:
              application/json:
                type: Customer
                example: !include examples/customerExample.raml
          404:
            body:
              application/json:
                example: {
                "message": "Error occured. Customer not found."
              }
      put:
        is:
          - noCache
          - isSecure
        headers:
          Client-ID:
            description: Identifier of the client invoking the API.
            required: true
        description: Update a customer by id
        body:
          application/json:
            type: Customer
            example: !include examples/customerExample.raml
        responses:
          200:
            body:
              application/json:
                type: Customer
                example: !include examples/customerExample.raml
          404:
            body:
              application/json:
                example: {
                "message": "Error occured. Customer not found."
              }
      delete:
        is:
          - noCache
          - isSecure
        headers:
          Client-ID:
            description: Identifier of the client invoking the API.
            required: true
        description: Delete a customer by id
        responses:
          204:
            description: Deleted successfully
            body:
              application/json:
                example: !include examples/customerExample.raml
                  
          404:
            body:
              application/json:
                example: {
                "message": "Error occured. Customer not found."
              }
  
  /orders:
    description: Order Resource. To be defined.
    get:
      responses:
        501:
          description: Error response signifying the API is yet to be introduced.
          body:
            application/json: 
              example: {
                "message" : "Method not implemented."
                }
              

  /products:
    description: Products Resource. To be defined.
    get:
      responses:
        501:
          description: Error response signifying the API is yet to be introduced.
          body:
            application/json: 
              example: {
                "message" : "Method not implemented."
                }
    
  